# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin "@tiptap/core", to: "https://ga.jspm.io/npm:@tiptap/core@2.1.16/dist/index.js"
pin "@tiptap/pm/commands", to: "https://ga.jspm.io/npm:@tiptap/pm@2.1.16/commands/dist/index.js"
pin "@tiptap/pm/keymap", to: "https://ga.jspm.io/npm:@tiptap/pm@2.1.16/keymap/dist/index.js"
pin "@tiptap/pm/model", to: "https://ga.jspm.io/npm:@tiptap/pm@2.1.16/model/dist/index.js"
pin "@tiptap/pm/schema-list", to: "https://ga.jspm.io/npm:@tiptap/pm@2.1.16/schema-list/dist/index.js"
pin "@tiptap/pm/state", to: "https://ga.jspm.io/npm:@tiptap/pm@2.1.16/state/dist/index.js"
pin "@tiptap/pm/transform", to: "https://ga.jspm.io/npm:@tiptap/pm@2.1.16/transform/dist/index.js"
pin "@tiptap/pm/view", to: "https://ga.jspm.io/npm:@tiptap/pm@2.1.16/view/dist/index.js"
pin "orderedmap", to: "https://ga.jspm.io/npm:orderedmap@2.1.1/dist/index.js"
pin "prosemirror-commands", to: "https://ga.jspm.io/npm:prosemirror-commands@1.5.2/dist/index.js"
pin "prosemirror-keymap", to: "https://ga.jspm.io/npm:prosemirror-keymap@1.2.2/dist/index.js"
pin "prosemirror-model", to: "https://ga.jspm.io/npm:prosemirror-model@1.19.4/dist/index.js"
pin "prosemirror-schema-list", to: "https://ga.jspm.io/npm:prosemirror-schema-list@1.3.0/dist/index.js"
pin "prosemirror-state", to: "https://ga.jspm.io/npm:prosemirror-state@1.4.3/dist/index.js"
pin "prosemirror-transform", to: "https://ga.jspm.io/npm:prosemirror-transform@1.8.0/dist/index.js"
pin "prosemirror-view", to: "https://ga.jspm.io/npm:prosemirror-view@1.32.7/dist/index.js"
pin "w3c-keyname", to: "https://ga.jspm.io/npm:w3c-keyname@2.2.8/index.js"
pin "@tiptap/starter-kit", to: "https://ga.jspm.io/npm:@tiptap/starter-kit@2.1.16/dist/index.js"
pin "@tiptap/extension-blockquote", to: "https://ga.jspm.io/npm:@tiptap/extension-blockquote@2.1.16/dist/index.js"
pin "@tiptap/extension-bold", to: "https://ga.jspm.io/npm:@tiptap/extension-bold@2.1.16/dist/index.js"
pin "@tiptap/extension-bullet-list", to: "https://ga.jspm.io/npm:@tiptap/extension-bullet-list@2.1.16/dist/index.js"
pin "@tiptap/extension-code", to: "https://ga.jspm.io/npm:@tiptap/extension-code@2.1.16/dist/index.js"
pin "@tiptap/extension-code-block", to: "https://ga.jspm.io/npm:@tiptap/extension-code-block@2.1.16/dist/index.js"
pin "@tiptap/extension-document", to: "https://ga.jspm.io/npm:@tiptap/extension-document@2.1.16/dist/index.js"
pin "@tiptap/extension-dropcursor", to: "https://ga.jspm.io/npm:@tiptap/extension-dropcursor@2.1.16/dist/index.js"
pin "@tiptap/extension-gapcursor", to: "https://ga.jspm.io/npm:@tiptap/extension-gapcursor@2.1.16/dist/index.js"
pin "@tiptap/extension-hard-break", to: "https://ga.jspm.io/npm:@tiptap/extension-hard-break@2.1.16/dist/index.js"
pin "@tiptap/extension-heading", to: "https://ga.jspm.io/npm:@tiptap/extension-heading@2.1.16/dist/index.js"
pin "@tiptap/extension-history", to: "https://ga.jspm.io/npm:@tiptap/extension-history@2.1.16/dist/index.js"
pin "@tiptap/extension-horizontal-rule", to: "https://ga.jspm.io/npm:@tiptap/extension-horizontal-rule@2.1.16/dist/index.js"
pin "@tiptap/extension-italic", to: "https://ga.jspm.io/npm:@tiptap/extension-italic@2.1.16/dist/index.js"
pin "@tiptap/extension-list-item", to: "https://ga.jspm.io/npm:@tiptap/extension-list-item@2.1.16/dist/index.js"
pin "@tiptap/extension-ordered-list", to: "https://ga.jspm.io/npm:@tiptap/extension-ordered-list@2.1.16/dist/index.js"
pin "@tiptap/extension-paragraph", to: "https://ga.jspm.io/npm:@tiptap/extension-paragraph@2.1.16/dist/index.js"
pin "@tiptap/extension-strike", to: "https://ga.jspm.io/npm:@tiptap/extension-strike@2.1.16/dist/index.js"
pin "@tiptap/extension-text", to: "https://ga.jspm.io/npm:@tiptap/extension-text@2.1.16/dist/index.js"
pin "@tiptap/pm/dropcursor", to: "https://ga.jspm.io/npm:@tiptap/pm@2.1.16/dropcursor/dist/index.js"
pin "@tiptap/pm/gapcursor", to: "https://ga.jspm.io/npm:@tiptap/pm@2.1.16/gapcursor/dist/index.js"
pin "@tiptap/pm/history", to: "https://ga.jspm.io/npm:@tiptap/pm@2.1.16/history/dist/index.js"
pin "prosemirror-dropcursor", to: "https://ga.jspm.io/npm:prosemirror-dropcursor@1.8.1/dist/index.js"
pin "prosemirror-gapcursor", to: "https://ga.jspm.io/npm:prosemirror-gapcursor@1.3.2/dist/index.js"
pin "prosemirror-history", to: "https://ga.jspm.io/npm:prosemirror-history@1.3.2/dist/index.js"
pin "rope-sequence", to: "https://ga.jspm.io/npm:rope-sequence@1.3.4/dist/index.js"
